version: '3'

services:

  survey:
    container_name: survey
    restart: always
    build:
      context: ./app
      dockerfile: Dockerfile

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 4242:80

